name: "Goodwe Inverter"
version: "0.1.2"
image: ghcr.io/voyanti/ha-goodwe
slug: "ha-goodwe"
description: "Goodwe Inverter Prebuilt"
init: false
startup: application
boot: auto
uart: true
usb: true
url: "https://github.com/Voyanti/ha-goodwe"
arch:
  - aarch64
  - amd64
options:
  servers:
    - name: Logger
      serialnum: USD0B4502B
      server_type: GOODWE_LOGGER
      connected_client: client1
      modbus_id: 1
  clients:
    - name: client1
      type: TCP
      host: 192.168.2.1
      port: 502
  pause_interval_seconds: 1
  midnight_sleep_enabled: true
  midnight_sleep_wakeup_after: 10
  mqtt_host: "localhost"
  mqtt_port: 1884
  # mqtt_host: "core-mosquitto"
  # mqtt_port: 1883
  mqtt_user: "mqtt"
  mqtt_password: "mqtt"
  mwtt_ha_discovery_topic: homeassistant
  mqtt_base_topic: modbus
  mqtt_reconnect_attempts: 5
schema:
  servers:
    - name: str
      serialnum: str
      server_type: list(GOODWE_LOGGER)
      connected_client: str
      modbus_id: int(0,255)
      # PT: int?
      # CT: int?
  clients:
    - name: str
      type: list(TCP|RTU)
      host: str?
      port: str?
      baudrate: int?
      bytesize: int?
      parity: bool?
      stopbits: int?
  pause_interval_seconds: float
  midnight_sleep_enabled: bool
  midnight_sleep_wakeup_after: int
  mqtt_host: str
  mqtt_port: port
  mqtt_user: str
  mqtt_password: password
  mwtt_ha_discovery_topic: str
  mqtt_base_topic: str
  mqtt_reconnect_attempts: int
